add exit function
s1f102201065/django-test-exercise pull request #11
Opened 2024-07-15 02:43 UTC by s1f102200031

終了機能を追加しました。
確認宜しくお願いします。何か間違っていたら御免。

2024-07-16 06:49 UTC, KentaShimodaira approved these changes
レビューしました

2024-07-16 07:39 UTC, 1f10230076 reviewed
ありがとうございます！

2024-07-16 08:55 UTC, s1f102201065 requested changes
コード自体に問題はありませんが消去機能のプルリクエストをマージした際に同じ行に異なる編集をしているためコンフリクトが発生しています。コンフリクトの解消をお願いします。

2024-07-17 01:36 UTC, s1f102200031 commented
コードの変更は出来ました。

2024-07-17 01:48 UTC, s1f102201065 commented on todo/templates/todo/detail.html
> +    div>
先頭の<が抜けているので修正してください

2024-07-17 02:02 UTC, s1f102200031 commented on todo/templates/todo/detail.html
> +    div>
指摘ありがとうございます。修正しました。

2024-07-18 02:52 UTC, s1f102201065 reviewed
確認しました。

2024-07-18 02:53 UTC, 1f10230076 commented
ありがとうございました

2024-07-18 02:54 UTC, s1f102201065 approved these changes
プルリクエストを承認します

2024-07-18 02:54 UTC, merged